
export default function handler(req, res) {
    res.status(200).json([
    { "value": "ABC da Construção", "label": "ABC da Construção" },
    { "value": "aec web", "label": "aec web" },
    { "value": "Alelo", "label": "Alelo" },
    { "value": "Americanas", "label": "Americanas" },
    { "value": "Americanas Marketplace", "label": "Americanas Marketplace" },
    { "value": "Anhanguera Ferramentas", "label": "Anhanguera Ferramentas" },
    { "value": "Artwalk", "label": "Artwalk" },
    { "value": "Authentic Feet", "label": "Authentic Feet" },
    { "value": "Bergamía", "label": "Bergamía" },
    { "value": "Bitcointrade", "label": "Bitcointrade" },
    { "value": "Bombay", "label": "Bombay" },
    { "value": "Brasil Brokers", "label": "Brasil Brokers" },
    { "value": "BTS Global", "label": "BTS Global" },
    { "value": "Buson", "label": "Buson" },
    { "value": "Chromatox", "label": "Chromatox" },
    { "value": "CNS Online", "label": "CNS Online" },
    { "value": "Cobasi", "label": "Cobasi" },
    { "value": "Comparamais", "label": "Comparamais" },
    { "value": "Conversion", "label": "Conversion" },
    { "value": "Copagaz", "label": "Copagaz" },
    { "value": "Costa Rica Colchões", "label": "Costa Rica Colchões" },
    { "value": "CrediHome", "label": "CrediHome" },
    { "value": "Descomplica", "label": "Descomplica" },
    { "value": "Dimona", "label": "Dimona" },
    { "value": "Direção Concursos", "label": "Direção Concursos" },
    { "value": "Educa Mais Brasil", "label": "Educa Mais Brasil" },
    { "value": "Elastobor", "label": "Elastobor" },
    { "value": "Empregos", "label": "Empregos" },
    { "value": "Estratégia Concursos", "label": "Estratégia Concursos" },
    { "value": "Eu Quero Investir", "label": "Eu Quero Investir" },
    { "value": "Evino", "label": "Evino" },
    { "value": "FinanZero", "label": "FinanZero" },
    { "value": "Flores Online", "label": "Flores Online" },
    { "value": "(GCS) Braz Cubas", "label": "(GCS) Braz Cubas" },
    { "value": "(GCS) CEUNSP", "label": "(GCS) CEUNSP" },
    { "value": "(GCS) Cruzeiro do Sul", "label": "(GCS) Cruzeiro do Sul" },
    { "value": "(GCS) Cruzeiro do Sul Virtual", "label": "(GCS) Cruzeiro do Sul Virtual" },
    { "value": "(GCS) FSG", "label": "(GCS) FSG" },
    { "value": "(GCS) Positivo", "label": "(GCS) Positivo" },
    { "value": "(GCS) UDF", "label": "(GCS) UDF" },
    { "value": "(GCS) UNICID", "label": "(GCS) UNICID" },
    { "value": "(GCS) UNIFRAN", "label": "(GCS) UNIFRAN" },
    { "value": "(GCS) UNIPÊ", "label": "(GCS) UNIPÊ" },
    { "value": "General Car", "label": "General Car" },
    { "value": "Gran Cursos Online", "label": "Gran Cursos Online" },
    { "value": "Growth Suplementos", "label": "Growth Suplementos" },
    { "value": "Guia dos Melhores", "label": "Guia dos Melhores" },
    { "value": "Hanes", "label": "Hanes" },
    { "value": "Icatu", "label": "Icatu" },
    { "value": "Iluminim", "label": "Iluminim" },
    { "value": "Instituto QR", "label": "Instituto QR" },
    { "value": "Isabela Flores", "label": "Isabela Flores" },
    { "value": "Lauton", "label": "Lauton" },
    { "value": "Lello Imóveis", "label": "Lello Imóveis" },
    { "value": "Liquigás", "label": "Liquigás" },
    { "value": "Localiza (Gestão de Frotas)", "label": "Localiza (Gestão de Frotas)" },
    { "value": "Localiza (Meoo)", "label": "Localiza (Meoo)" },
    { "value": "Localiza (RAC)", "label": "Localiza (RAC)" },
    { "value": "Localiza (Seminovos)", "label": "Localiza (Seminovos)" },
    { "value": "Localiza (ZARP)", "label": "Localiza (ZARP)" },
    { "value": "Lucree", "label": "Lucree" },
    { "value": "Magicfeet", "label": "Magicfeet" },
    { "value": "Melhor Câmbio", "label": "Melhor Câmbio" },
    { "value": "Meu Financiamento Solar", "label": "Meu Financiamento Solar" },
    { "value": "Mills", "label": "Mills" },
    { "value": "https://www.mundodacarabina.com.br/", "label": "Mundo da Carabina" },
    { "value": "Olho no Carro", "label": "Olho no Carro" },
    { "value": "Órigo Energia", "label": "Órigo Energia" },
    { "value": "Palácio das Ferramentas", "label": "Palácio das Ferramentas" },
    { "value": "Portal Solar", "label": "Portal Solar" },
    { "value": "Preply", "label": "Preply" },
    { "value": "Ri Happy", "label": "Ri Happy" },
    { "value": "Saldão da Informática", "label": "Saldão da Informática" },
    { "value": "Serasa", "label": "Serasa" },
    { "value": "Serasa Certificado Digital", "label": "Serasa Certificado Digital" },
    { "value": "Serasa Experian", "label": "Serasa Experian" },
    { "value": "ShopFácil", "label": "ShopFácil" },
    { "value": "Sodré Santoro", "label": "Sodré Santoro" },
    { "value": "Sorte Online", "label": "Sorte Online" },
    { "value": "Sterilair", "label": "Sterilair" },
    { "value": "Submarino", "label": "Submarino" },
    { "value": "Ticket Log", "label": "Ticket Log" },
    { "value": "Track.co", "label": "Track.co" },
    { "value": "Universal Software", "label": "Universal Software" },
    { "value": "Viajanet", "label": "Viajanet" },
    { "value": "Vialaser", "label": "Vialaser" },
    { "value": "Zenklub", "label": "Zenklub" },
    { "value": "Zenvia", "label": "Zenvia" },
    { "value": "Zenvia México", "label": "Zenvia México" }
])
}