
export default function handler(req, res) {
    res.status(200).json([{ "value": 22, "label": "ABC da Construção" },
    { "value": 311, "label": "aec web" },
    { "value": 12, "label": "Alelo" },
    { "value": 181, "label": "Americanas" },
    { "value": 345, "label": "Americanas Marketplace" },
    { "value": 27, "label": "Anhanguera Ferramentas" },
    { "value": 38, "label": "Artwalk" },
    { "value": 37, "label": "Authentic Feet" },
    { "value": 242, "label": "Bergamía" },
    { "value": 13, "label": "Bitcointrade" },
    { "value": 344, "label": "Bombay" },
    { "value": 341, "label": "Brasil Brokers" },
    { "value": 324, "label": "BTS Global" },
    { "value": 411, "label": "Buson" },
    { "value": 191, "label": "Chromatox" },
    { "value": 121, "label": "CNS Online" },
    { "value": 57, "label": "Cobasi" },
    { "value": 112, "label": "Comparamais" },
    { "value": 55, "label": "Conversion" },
    { "value": 29, "label": "Copagaz" },
    { "value": 44, "label": "Costa Rica Colchões" },
    { "value": 331, "label": "CrediHome" },
    { "value": 251, "label": "Descomplica" },
    { "value": 23, "label": "Dimona" },
    { "value": 161, "label": "Direção Concursos" },
    { "value": 241, "label": "Educa Mais Brasil" },
    { "value": 94, "label": "Elastobor" },
    { "value": 59, "label": "Empregos" },
    { "value": 131, "label": "Estratégia Concursos" },
    { "value": 211, "label": "Eu Quero Investir" },
    { "value": 58, "label": "Evino" },
    { "value": 96, "label": "FinanZero" },
    { "value": 41, "label": "Flores Online" },
    { "value": 95, "label": "(GCS) Braz Cubas" },
    { "value": 48, "label": "(GCS) CEUNSP" },
    { "value": 26, "label": "(GCS) Cruzeiro do Sul" },
    { "value": 20, "label": "(GCS) Cruzeiro do Sul Virtual" },
    { "value": 49, "label": "(GCS) FSG" },
    { "value": 100, "label": "(GCS) Positivo" },
    { "value": 34, "label": "(GCS) UDF" },
    { "value": 33, "label": "(GCS) UNICID" },
    { "value": 47, "label": "(GCS) UNIFRAN" },
    { "value": 46, "label": "(GCS) UNIPÊ" },
    { "value": 21, "label": "General Car" },
    { "value": 1, "label": "Gran Cursos Online" },
    { "value": 3, "label": "Growth Suplementos" },
    { "value": 431, "label": "Guia dos Melhores" },
    { "value": 30, "label": "Hanes" },
    { "value": 205, "label": "Icatu" },
    { "value": 111, "label": "Iluminim" },
    { "value": 291, "label": "Instituto QR" },
    { "value": 43, "label": "Isabela Flores" },
    { "value": 323, "label": "Lauton" },
    { "value": 81, "label": "Lello Imóveis" },
    { "value": 204, "label": "Liquigás" },
    { "value": 302, "label": "Localiza (Gestão de Frotas)" },
    { "value": 18, "label": "Localiza (Meoo)" },
    { "value": 10, "label": "Localiza (RAC)" },
    { "value": 214, "label": "Localiza (Seminovos)" },
    { "value": 16, "label": "Localiza (ZARP)" },
    { "value": 261, "label": "Lucree" },
    { "value": 39, "label": "Magicfeet" },
    { "value": 183, "label": "Melhor Câmbio" },
    { "value": 347, "label": "Meu Financiamento Solar" },
    { "value": 343, "label": "Mills" },
    { "value": 19, "label": "Mundo da Carabina" },
    { "value": 346, "label": "Olho no Carro" },
    { "value": 342, "label": "Órigo Energia" },
    { "value": 14, "label": "Palácio das Ferramentas" },
    { "value": 321, "label": "Portal Solar" },
    { "value": 422, "label": "Preply" },
    { "value": 271, "label": "Ri Happy" },
    { "value": 35, "label": "Saldão da Informática" },
    { "value": 6, "label": "Serasa" },
    { "value": 272, "label": "Serasa Certificado Digital" },
    { "value": 92, "label": "Serasa Experian" },
    { "value": 8, "label": "ShopFácil" },
    { "value": 9, "label": "Sodré Santoro" },
    { "value": 245, "label": "Sorte Online" },
    { "value": 40, "label": "Sterilair" },
    { "value": 182, "label": "Submarino" },
    { "value": 212, "label": "Ticket Log" },
    { "value": 281, "label": "Track.co" },
    { "value": 301, "label": "Universal Software" },
    { "value": 7, "label": "Viajanet" },
    { "value": 213, "label": "Vialaser" },
    { "value": 56, "label": "Zenklub" },
    { "value": 17, "label": "Zenvia" },
    { "value": 98, "label": "Zenvia México" }])
}